# Setup CI to checkout submodules
variables:
  GIT_SUBMODULE_STRATEGY: recursive
stages:
    - build_container
    - build_tvm
    - test_unit
    - test_e2e

build_container:
    stage: build_container
    image: quay.io/containers/podman
    script:
      - sudo podman login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
      - sudo podman pull $CI_REGISTRY_IMAGE:latest || true
      - sudo podman build --cache-from $CI_REGISTRY_IMAGE --tag $CI_REGISTRY_IMAGE:$CI_COMMIT_SHA --tag $CI_REGISTRY_IMAGE:latest -f diana/docker/Dockerfile.tvm .
      - sudo podman push $CI_REGISTRY_IMAGE:$CI_COMMIT_SHA
      - sudo podman push $CI_REGISTRY_IMAGE:latest
    tags:
      - podman

build_tvm_release:
    stage: build_tvm
    image: $CI_REGISTRY_IMAGE:latest
    script:
      - mkdir build
      - cp diana/config.cmake build
      - cd build
      - cmake ..
      - make -j 10
      - cd ..
    artifacts:
      paths:
        - build
    tags:
      - podman

pytest_unit:
    stage: test_unit
    image: $CI_REGISTRY_IMAGE:latest
    dependencies: 
      - build_tvm_release
    script:
      - pytest tests/python/contrib/test_soma_dory --junitxml=test_unit_report.xml
    artifacts:
       when: always
       reports:
          junit: test_unit_report.xml
    tags:
      - podman

pytest_e2e:
    stage: test_e2e
    image: $CI_REGISTRY_IMAGE:latest
    dependencies: 
      - build_tvm_release
    script:
      - cd diana/byoc
      - echo "Dory version is "`git --git-dir /dory/.git rev-parse HEAD`
      - bash copy_dory_files.sh
      - pytest -v test.py --junitxml=test_e2e_report.xml
    artifacts:
       when: always
       reports:
          junit: diana/byoc/test_e2e_report.xml
    tags:
      - podman
