# Setup CI to checkout submodules
variables:
  GIT_SUBMODULE_STRATEGY: recursive
stages:
  - build

build_tvm_fork:
    stage: build
    image: ubuntu:20.04
    variables:
      DEBIAN_FRONTEND: noninteractive
    script:
      - cd tvm-fork
      - apt-get update && apt-get install -y python3 python3-dev python3-setuptools gcc libtinfo-dev zlib1g-dev build-essential cmake libedit-dev libxml2-dev -y
      - mkdir build
      - cp sirius/config.cmake build
      - cd build
      - cmake ..
      - make -j12
      - pip3 install virtualenv
      - virtualenv venv
      - source venv/bin/activate
      - cd python
      - python setup.py
      - cd ..
      - pip3 install -r sirius/requirements.txt
    artifacts:
      paths:
        - tvm-fork/build/
        - tvm-fork/venv/
    tags:
      - podman
