# Setup CI to checkout submodules
variables:
  GIT_SUBMODULE_STRATEGY: recursive
stages:
    - build_container
    - build_tvm
    - test_htvm

build_container:
    stage: build_container
    image: quay.io/containers/podman
    script:
      - sudo podman login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
      - sudo podman pull $CI_REGISTRY_IMAGE:latest || true
      - sudo podman build --cache-from $CI_REGISTRY_IMAGE --tag $CI_REGISTRY_IMAGE:$CI_COMMIT_SHA --tag $CI_REGISTRY_IMAGE:latest -f diana/docker/Dockerfile.tvm .
      - sudo podman push $CI_REGISTRY_IMAGE:$CI_COMMIT_SHA
      - sudo podman push $CI_REGISTRY_IMAGE:latest
    tags:
      - podman

build_tvm_release:
    stage: build_tvm
    image: $CI_REGISTRY_IMAGE:latest
    script:
      - mkdir build
      - cp diana/config.cmake build
      - cd build
      - cmake ..
      - make -j 10
      - cd ..
    artifacts:
      paths:
        - build
    tags:
      - podman

pytest:
    stage: test_htvm
    image: $CI_REGISTRY_IMAGE:latest
    dependencies: 
      - build_tvm_release
    script:
      - export TVM_HOME=`pwd`
      - export PYTHONPATH=`pwd`/python
      - cd diana/byoc
      - echo "Dory version is "`git --git-dir /dory/.git rev-parse HEAD`
      - bash copy_dory_files.sh
      - pytest -v test.py --junitxml=test_report.xml
    artifacts:
       when: always
       reports:
          junit: /tvm-fork/diana/byoc/test_report.xml
    tags:
      - podman
