# Setup CI to checkout submodules
variables:
  GIT_SUBMODULE_STRATEGY: recursive
stages:
    - build_container
    - build_tvm
    - codegen_c
    - codegen_soma_dory
    - build_utvm
    - test_utvm

build_container:
    stage: build_container
    image: quay.io/containers/podman
    script:
      - sudo podman login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
      - sudo podman pull $CI_REGISTRY_IMAGE:latest || true
      - sudo podman build --cache-from $CI_REGISTRY_IMAGE --tag $CI_REGISTRY_IMAGE:$CI_COMMIT_SHA --tag $CI_REGISTRY_IMAGE:latest -f sirius/docker/Dockerfile.tvm .
      - sudo podman push $CI_REGISTRY_IMAGE:$CI_COMMIT_SHA
      - sudo podman push $CI_REGISTRY_IMAGE:latest
    tags:
      - podman

build_tvm_release:
    stage: build_tvm
    image: $CI_REGISTRY_IMAGE:latest
    script:
      - mkdir build
      - cp sirius/config.cmake build
      - cd build
      - cmake ..
      - make -j 10
      - cd ..
    artifacts:
      paths:
        - build
    tags:
      - podman

compile_relay_simple_c:
    stage: codegen_c
    image: $CI_REGISTRY_IMAGE:latest
    dependencies: 
      - build_tvm_release
    script:
      - export TVM_HOME=`pwd`
      - export PYTHONPATH=`pwd`/python
      - cd sirius/byoc
      - python3 relay_simple.py --c
    artifacts:
      paths:
        - sirius/byoc/build
        - sirius/byoc/include
        - sirius/byoc/src
    tags:
      - podman

compile_relay_simple_soma_dory:
    stage: codegen_soma_dory
    image: $CI_REGISTRY_IMAGE:latest
    dependencies: 
      - build_tvm_release
    script:
      - export TVM_HOME=`pwd`
      - export PYTHONPATH=`pwd`/python
      - cd sirius/byoc
      - python3 relay_simple.py --soma_dory
      - sh copy_dory_files.sh
    artifacts:
      paths:
        - sirius/byoc/dory
        - sirius/byoc/build
        - sirius/byoc/include
        - sirius/byoc/src
    tags:
      - podman


build_relay_simple_c:
    stage: build_utvm
    image: $CI_REGISTRY_IMAGE:latest
    dependencies:
      - compile_relay_simple_c
    script:
      - cd sirius/byoc
      - make -f Makefile.x86 all
    artifacts:
      paths:
        - sirius/byoc/build/demo
    tags:
      - podman

run_relay_simple_c:
    stage: test_utvm
    image: $CI_REGISTRY_IMAGE:latest
    dependencies:
      - build_relay_simple_c
    script:
      - sirius/byoc/build/demo
    tags:
      - podman


compile_relay_resnet20_c:
    stage: codegen_c
    image: $CI_REGISTRY_IMAGE:latest
    dependencies: 
      - build_tvm_release
    script:
      - export TVM_HOME=`pwd`
      - export PYTHONPATH=`pwd`/python
      - cd sirius/byoc
      - python3 relay_resnet20.py --c
    artifacts:
      paths:
        - sirius/byoc/build
        - sirius/byoc/include
        - sirius/byoc/src
    tags:
      - podman

compile_relay_resnet20_soma_dory:
    stage: codegen_soma_dory
    image: $CI_REGISTRY_IMAGE:latest
    dependencies: 
      - build_tvm_release
    script:
      - export TVM_HOME=`pwd`
      - export PYTHONPATH=`pwd`/python
      - cd sirius/byoc
      - python3 relay_resnet20.py --soma_dory
      - sh copy_dory_files.sh
    artifacts:
      paths:
        - sirius/byoc/dory
        - sirius/byoc/build
        - sirius/byoc/include
        - sirius/byoc/src
    tags:
      - podman


build_relay_resnet20_c:
    stage: build_utvm
    image: $CI_REGISTRY_IMAGE:latest
    dependencies:
      - compile_relay_resnet20_c
    script:
      - cd sirius/byoc
      - make -f Makefile.x86 all
    artifacts:
      paths:
        - sirius/byoc/build/demo
    tags:
      - podman

run_relay_resnet20_c:
    stage: test_utvm
    image: $CI_REGISTRY_IMAGE:latest
    dependencies:
      - build_relay_resnet20_c
    script:
      - sirius/byoc/build/demo
    tags:
      - podman
