# Setup CI to checkout submodules
variables:
  GIT_SUBMODULE_STRATEGY: recursive
stages:
  - build

build_tvm_fork:
    stage: build
    image: quay.io/containers/podman
    script:
      - sudo podman login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
      - sudo podman pull $CI_REGISTRY_IMAGE:latest || true
      - sudo podman build --cache-from $CI_REGISTRY_IMAGE:latest --tag $CI_REGISTRY_IMAGE:$CI_COMMIT_SHA --tag $CI_REGISTRY_IMAGE:latest -f sirius/docker/Dockerfile.tvm .
      - sudo podman push $CI_REGISTRY_IMAGE:$CI_COMMIT_SHA
      - sudo podman push $CI_REGISTRY_IMAGE:latest
    tags:
      - podman
